/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TrialEndedRouteImport } from './routes/trial-ended'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SnagsIndexRouteImport } from './routes/snags.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SubcontractorsNewRouteImport } from './routes/subcontractors.new'
import { Route as SubcontractorProjectIdRouteImport } from './routes/subcontractor.$projectId'
import { Route as SnagsNewRouteImport } from './routes/snags.new'
import { Route as SnagsSnagIdRouteImport } from './routes/snags.$snagId'
import { Route as SiteManagerProjectIdRouteImport } from './routes/site-manager.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProgrammeProjectIdRouteImport } from './routes/programme.$projectId'
import { Route as OrgNewRouteImport } from './routes/org.new'
import { Route as OrgOrgIdRouteImport } from './routes/org.$orgId'
import { Route as JoinOrgSlugRouteImport } from './routes/join-org.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DabsProjectIdRouteImport } from './routes/dabs.$projectId'
import { Route as BillingProjectIdRouteImport } from './routes/billing.$projectId'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiDrawingDrawingIdRouteImport } from './routes/api/drawing.$drawingId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicHooksWeatherSnapshotRouteImport } from './routes/api/public/hooks/weather-snapshot'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialEndedRoute = TrialEndedRouteImport.update({
  id: '/trial-ended',
  path: '/trial-ended',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SnagsIndexRoute = SnagsIndexRouteImport.update({
  id: '/snags/',
  path: '/snags/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractorsNewRoute = SubcontractorsNewRouteImport.update({
  id: '/subcontractors/new',
  path: '/subcontractors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractorProjectIdRoute = SubcontractorProjectIdRouteImport.update({
  id: '/subcontractor/$projectId',
  path: '/subcontractor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SnagsNewRoute = SnagsNewRouteImport.update({
  id: '/snags/new',
  path: '/snags/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SnagsSnagIdRoute = SnagsSnagIdRouteImport.update({
  id: '/snags/$snagId',
  path: '/snags/$snagId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteManagerProjectIdRoute = SiteManagerProjectIdRouteImport.update({
  id: '/site-manager/$projectId',
  path: '/site-manager/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeProjectIdRoute = ProgrammeProjectIdRouteImport.update({
  id: '/programme/$projectId',
  path: '/programme/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgNewRoute = OrgNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrgRoute,
} as any)
const OrgOrgIdRoute = OrgOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => OrgRoute,
} as any)
const JoinOrgSlugRoute = JoinOrgSlugRouteImport.update({
  id: '/join-org/$slug',
  path: '/join-org/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DabsProjectIdRoute = DabsProjectIdRouteImport.update({
  id: '/dabs/$projectId',
  path: '/dabs/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingProjectIdRoute = BillingProjectIdRouteImport.update({
  id: '/billing/$projectId',
  path: '/billing/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDrawingDrawingIdRoute = ApiDrawingDrawingIdRouteImport.update({
  id: '/api/drawing/$drawingId',
  path: '/api/drawing/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeatherSnapshotRoute =
  ApiPublicHooksWeatherSnapshotRouteImport.update({
    id: '/api/public/hooks/weather-snapshot',
    path: '/api/public/hooks/weather-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/experience': typeof ExperienceRoute
  '/mcp': typeof McpRoute
  '/oracle': typeof OracleRoute
  '/org': typeof OrgRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trial-ended': typeof TrialEndedRoute
  '/unlock': typeof UnlockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing/$projectId': typeof BillingProjectIdRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join-org/$slug': typeof JoinOrgSlugRoute
  '/org/$orgId': typeof OrgOrgIdRoute
  '/org/new': typeof OrgNewRoute
  '/programme/$projectId': typeof ProgrammeProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/snags/$snagId': typeof SnagsSnagIdRoute
  '/snags/new': typeof SnagsNewRoute
  '/subcontractor/$projectId': typeof SubcontractorProjectIdRoute
  '/subcontractors/new': typeof SubcontractorsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/snags/': typeof SnagsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
  '/api/public/hooks/weather-snapshot': typeof ApiPublicHooksWeatherSnapshotRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/experience': typeof ExperienceRoute
  '/mcp': typeof McpRoute
  '/oracle': typeof OracleRoute
  '/org': typeof OrgRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trial-ended': typeof TrialEndedRoute
  '/unlock': typeof UnlockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing/$projectId': typeof BillingProjectIdRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join-org/$slug': typeof JoinOrgSlugRoute
  '/org/$orgId': typeof OrgOrgIdRoute
  '/org/new': typeof OrgNewRoute
  '/programme/$projectId': typeof ProgrammeProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/snags/$snagId': typeof SnagsSnagIdRoute
  '/snags/new': typeof SnagsNewRoute
  '/subcontractor/$projectId': typeof SubcontractorProjectIdRoute
  '/subcontractors/new': typeof SubcontractorsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/snags': typeof SnagsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
  '/api/public/hooks/weather-snapshot': typeof ApiPublicHooksWeatherSnapshotRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/experience': typeof ExperienceRoute
  '/mcp': typeof McpRoute
  '/oracle': typeof OracleRoute
  '/org': typeof OrgRouteWithChildren
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trial-ended': typeof TrialEndedRoute
  '/unlock': typeof UnlockRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/billing/$projectId': typeof BillingProjectIdRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join-org/$slug': typeof JoinOrgSlugRoute
  '/org/$orgId': typeof OrgOrgIdRoute
  '/org/new': typeof OrgNewRoute
  '/programme/$projectId': typeof ProgrammeProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/snags/$snagId': typeof SnagsSnagIdRoute
  '/snags/new': typeof SnagsNewRoute
  '/subcontractor/$projectId': typeof SubcontractorProjectIdRoute
  '/subcontractors/new': typeof SubcontractorsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/snags/': typeof SnagsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
  '/api/public/hooks/weather-snapshot': typeof ApiPublicHooksWeatherSnapshotRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/experience'
    | '/mcp'
    | '/oracle'
    | '/org'
    | '/pricing'
    | '/reset-password'
    | '/trial-ended'
    | '/unlock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing/$projectId'
    | '/dabs/$projectId'
    | '/invite/$token'
    | '/join-org/$slug'
    | '/org/$orgId'
    | '/org/new'
    | '/programme/$projectId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/snags/$snagId'
    | '/snags/new'
    | '/subcontractor/$projectId'
    | '/subcontractors/new'
    | '/projects/'
    | '/snags/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/drawing/$drawingId'
    | '/api/public/hooks/weather-snapshot'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/experience'
    | '/mcp'
    | '/oracle'
    | '/org'
    | '/pricing'
    | '/reset-password'
    | '/trial-ended'
    | '/unlock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing/$projectId'
    | '/dabs/$projectId'
    | '/invite/$token'
    | '/join-org/$slug'
    | '/org/$orgId'
    | '/org/new'
    | '/programme/$projectId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/snags/$snagId'
    | '/snags/new'
    | '/subcontractor/$projectId'
    | '/subcontractors/new'
    | '/projects'
    | '/snags'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/drawing/$drawingId'
    | '/api/public/hooks/weather-snapshot'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/experience'
    | '/mcp'
    | '/oracle'
    | '/org'
    | '/pricing'
    | '/reset-password'
    | '/trial-ended'
    | '/unlock'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/billing/$projectId'
    | '/dabs/$projectId'
    | '/invite/$token'
    | '/join-org/$slug'
    | '/org/$orgId'
    | '/org/new'
    | '/programme/$projectId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/snags/$snagId'
    | '/snags/new'
    | '/subcontractor/$projectId'
    | '/subcontractors/new'
    | '/projects/'
    | '/snags/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/drawing/$drawingId'
    | '/api/public/hooks/weather-snapshot'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ExperienceRoute: typeof ExperienceRoute
  McpRoute: typeof McpRoute
  OracleRoute: typeof OracleRoute
  OrgRoute: typeof OrgRouteWithChildren
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrialEndedRoute: typeof TrialEndedRoute
  UnlockRoute: typeof UnlockRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BillingProjectIdRoute: typeof BillingProjectIdRoute
  DabsProjectIdRoute: typeof DabsProjectIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinOrgSlugRoute: typeof JoinOrgSlugRoute
  ProgrammeProjectIdRoute: typeof ProgrammeProjectIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SiteManagerProjectIdRoute: typeof SiteManagerProjectIdRoute
  SnagsSnagIdRoute: typeof SnagsSnagIdRoute
  SnagsNewRoute: typeof SnagsNewRoute
  SubcontractorProjectIdRoute: typeof SubcontractorProjectIdRoute
  SubcontractorsNewRoute: typeof SubcontractorsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  SnagsIndexRoute: typeof SnagsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiDrawingDrawingIdRoute: typeof ApiDrawingDrawingIdRoute
  ApiPublicHooksWeatherSnapshotRoute: typeof ApiPublicHooksWeatherSnapshotRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial-ended': {
      id: '/trial-ended'
      path: '/trial-ended'
      fullPath: '/trial-ended'
      preLoaderRoute: typeof TrialEndedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snags/': {
      id: '/snags/'
      path: '/snags'
      fullPath: '/snags/'
      preLoaderRoute: typeof SnagsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontractors/new': {
      id: '/subcontractors/new'
      path: '/subcontractors/new'
      fullPath: '/subcontractors/new'
      preLoaderRoute: typeof SubcontractorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontractor/$projectId': {
      id: '/subcontractor/$projectId'
      path: '/subcontractor/$projectId'
      fullPath: '/subcontractor/$projectId'
      preLoaderRoute: typeof SubcontractorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snags/new': {
      id: '/snags/new'
      path: '/snags/new'
      fullPath: '/snags/new'
      preLoaderRoute: typeof SnagsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snags/$snagId': {
      id: '/snags/$snagId'
      path: '/snags/$snagId'
      fullPath: '/snags/$snagId'
      preLoaderRoute: typeof SnagsSnagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-manager/$projectId': {
      id: '/site-manager/$projectId'
      path: '/site-manager/$projectId'
      fullPath: '/site-manager/$projectId'
      preLoaderRoute: typeof SiteManagerProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme/$projectId': {
      id: '/programme/$projectId'
      path: '/programme/$projectId'
      fullPath: '/programme/$projectId'
      preLoaderRoute: typeof ProgrammeProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/new': {
      id: '/org/new'
      path: '/new'
      fullPath: '/org/new'
      preLoaderRoute: typeof OrgNewRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/$orgId': {
      id: '/org/$orgId'
      path: '/$orgId'
      fullPath: '/org/$orgId'
      preLoaderRoute: typeof OrgOrgIdRouteImport
      parentRoute: typeof OrgRoute
    }
    '/join-org/$slug': {
      id: '/join-org/$slug'
      path: '/join-org/$slug'
      fullPath: '/join-org/$slug'
      preLoaderRoute: typeof JoinOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dabs/$projectId': {
      id: '/dabs/$projectId'
      path: '/dabs/$projectId'
      fullPath: '/dabs/$projectId'
      preLoaderRoute: typeof DabsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/$projectId': {
      id: '/billing/$projectId'
      path: '/billing/$projectId'
      fullPath: '/billing/$projectId'
      preLoaderRoute: typeof BillingProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawing/$drawingId': {
      id: '/api/drawing/$drawingId'
      path: '/api/drawing/$drawingId'
      fullPath: '/api/drawing/$drawingId'
      preLoaderRoute: typeof ApiDrawingDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weather-snapshot': {
      id: '/api/public/hooks/weather-snapshot'
      path: '/api/public/hooks/weather-snapshot'
      fullPath: '/api/public/hooks/weather-snapshot'
      preLoaderRoute: typeof ApiPublicHooksWeatherSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OrgRouteChildren {
  OrgOrgIdRoute: typeof OrgOrgIdRoute
  OrgNewRoute: typeof OrgNewRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgOrgIdRoute: OrgOrgIdRoute,
  OrgNewRoute: OrgNewRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ExperienceRoute: ExperienceRoute,
  McpRoute: McpRoute,
  OracleRoute: OracleRoute,
  OrgRoute: OrgRouteWithChildren,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrialEndedRoute: TrialEndedRoute,
  UnlockRoute: UnlockRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BillingProjectIdRoute: BillingProjectIdRoute,
  DabsProjectIdRoute: DabsProjectIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinOrgSlugRoute: JoinOrgSlugRoute,
  ProgrammeProjectIdRoute: ProgrammeProjectIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SiteManagerProjectIdRoute: SiteManagerProjectIdRoute,
  SnagsSnagIdRoute: SnagsSnagIdRoute,
  SnagsNewRoute: SnagsNewRoute,
  SubcontractorProjectIdRoute: SubcontractorProjectIdRoute,
  SubcontractorsNewRoute: SubcontractorsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  SnagsIndexRoute: SnagsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiDrawingDrawingIdRoute: ApiDrawingDrawingIdRoute,
  ApiPublicHooksWeatherSnapshotRoute: ApiPublicHooksWeatherSnapshotRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
