/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SiteManagerProjectIdRouteImport } from './routes/site-manager.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DabsProjectIdRouteImport } from './routes/dabs.$projectId'
import { Route as ApiDrawingDrawingIdRouteImport } from './routes/api/drawing.$drawingId'

const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteManagerProjectIdRoute = SiteManagerProjectIdRouteImport.update({
  id: '/site-manager/$projectId',
  path: '/site-manager/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DabsProjectIdRoute = DabsProjectIdRouteImport.update({
  id: '/dabs/$projectId',
  path: '/dabs/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingDrawingIdRoute = ApiDrawingDrawingIdRouteImport.update({
  id: '/api/drawing/$drawingId',
  path: '/api/drawing/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oracle': typeof OracleRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oracle': typeof OracleRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oracle': typeof OracleRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oracle'
    | '/dabs/$projectId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/projects/'
    | '/api/drawing/$drawingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/oracle'
    | '/dabs/$projectId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/projects'
    | '/api/drawing/$drawingId'
  id:
    | '__root__'
    | '/'
    | '/oracle'
    | '/dabs/$projectId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/projects/'
    | '/api/drawing/$drawingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OracleRoute: typeof OracleRoute
  DabsProjectIdRoute: typeof DabsProjectIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SiteManagerProjectIdRoute: typeof SiteManagerProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiDrawingDrawingIdRoute: typeof ApiDrawingDrawingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-manager/$projectId': {
      id: '/site-manager/$projectId'
      path: '/site-manager/$projectId'
      fullPath: '/site-manager/$projectId'
      preLoaderRoute: typeof SiteManagerProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dabs/$projectId': {
      id: '/dabs/$projectId'
      path: '/dabs/$projectId'
      fullPath: '/dabs/$projectId'
      preLoaderRoute: typeof DabsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawing/$drawingId': {
      id: '/api/drawing/$drawingId'
      path: '/api/drawing/$drawingId'
      fullPath: '/api/drawing/$drawingId'
      preLoaderRoute: typeof ApiDrawingDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OracleRoute: OracleRoute,
  DabsProjectIdRoute: DabsProjectIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SiteManagerProjectIdRoute: SiteManagerProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiDrawingDrawingIdRoute: ApiDrawingDrawingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
