/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SubcontractorsNewRouteImport } from './routes/subcontractors.new'
import { Route as SubcontractorProjectIdRouteImport } from './routes/subcontractor.$projectId'
import { Route as SiteManagerProjectIdRouteImport } from './routes/site-manager.$projectId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DabsProjectIdRouteImport } from './routes/dabs.$projectId'
import { Route as ApiDrawingDrawingIdRouteImport } from './routes/api/drawing.$drawingId'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractorsNewRoute = SubcontractorsNewRouteImport.update({
  id: '/subcontractors/new',
  path: '/subcontractors/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubcontractorProjectIdRoute = SubcontractorProjectIdRouteImport.update({
  id: '/subcontractor/$projectId',
  path: '/subcontractor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteManagerProjectIdRoute = SiteManagerProjectIdRouteImport.update({
  id: '/site-manager/$projectId',
  path: '/site-manager/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DabsProjectIdRoute = DabsProjectIdRouteImport.update({
  id: '/dabs/$projectId',
  path: '/dabs/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrawingDrawingIdRoute = ApiDrawingDrawingIdRouteImport.update({
  id: '/api/drawing/$drawingId',
  path: '/api/drawing/$drawingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/oracle': typeof OracleRoute
  '/unlock': typeof UnlockRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/subcontractor/$projectId': typeof SubcontractorProjectIdRoute
  '/subcontractors/new': typeof SubcontractorsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/oracle': typeof OracleRoute
  '/unlock': typeof UnlockRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/subcontractor/$projectId': typeof SubcontractorProjectIdRoute
  '/subcontractors/new': typeof SubcontractorsNewRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/oracle': typeof OracleRoute
  '/unlock': typeof UnlockRoute
  '/dabs/$projectId': typeof DabsProjectIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/site-manager/$projectId': typeof SiteManagerProjectIdRoute
  '/subcontractor/$projectId': typeof SubcontractorProjectIdRoute
  '/subcontractors/new': typeof SubcontractorsNewRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/drawing/$drawingId': typeof ApiDrawingDrawingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/oracle'
    | '/unlock'
    | '/dabs/$projectId'
    | '/invite/$token'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/subcontractor/$projectId'
    | '/subcontractors/new'
    | '/projects/'
    | '/api/drawing/$drawingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/oracle'
    | '/unlock'
    | '/dabs/$projectId'
    | '/invite/$token'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/subcontractor/$projectId'
    | '/subcontractors/new'
    | '/projects'
    | '/api/drawing/$drawingId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/oracle'
    | '/unlock'
    | '/dabs/$projectId'
    | '/invite/$token'
    | '/projects/$projectId'
    | '/projects/new'
    | '/site-manager/$projectId'
    | '/subcontractor/$projectId'
    | '/subcontractors/new'
    | '/projects/'
    | '/api/drawing/$drawingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  OracleRoute: typeof OracleRoute
  UnlockRoute: typeof UnlockRoute
  DabsProjectIdRoute: typeof DabsProjectIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  SiteManagerProjectIdRoute: typeof SiteManagerProjectIdRoute
  SubcontractorProjectIdRoute: typeof SubcontractorProjectIdRoute
  SubcontractorsNewRoute: typeof SubcontractorsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiDrawingDrawingIdRoute: typeof ApiDrawingDrawingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontractors/new': {
      id: '/subcontractors/new'
      path: '/subcontractors/new'
      fullPath: '/subcontractors/new'
      preLoaderRoute: typeof SubcontractorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subcontractor/$projectId': {
      id: '/subcontractor/$projectId'
      path: '/subcontractor/$projectId'
      fullPath: '/subcontractor/$projectId'
      preLoaderRoute: typeof SubcontractorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-manager/$projectId': {
      id: '/site-manager/$projectId'
      path: '/site-manager/$projectId'
      fullPath: '/site-manager/$projectId'
      preLoaderRoute: typeof SiteManagerProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dabs/$projectId': {
      id: '/dabs/$projectId'
      path: '/dabs/$projectId'
      fullPath: '/dabs/$projectId'
      preLoaderRoute: typeof DabsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drawing/$drawingId': {
      id: '/api/drawing/$drawingId'
      path: '/api/drawing/$drawingId'
      fullPath: '/api/drawing/$drawingId'
      preLoaderRoute: typeof ApiDrawingDrawingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  OracleRoute: OracleRoute,
  UnlockRoute: UnlockRoute,
  DabsProjectIdRoute: DabsProjectIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  SiteManagerProjectIdRoute: SiteManagerProjectIdRoute,
  SubcontractorProjectIdRoute: SubcontractorProjectIdRoute,
  SubcontractorsNewRoute: SubcontractorsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiDrawingDrawingIdRoute: ApiDrawingDrawingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
